### ISSUE TITLE
echart需添加参数

### ISSUE THREAD

**Issue by aym19900825** [hklhai/dashboard#26]
[https://app.zenhub.com/files/152548651/eb612835-6935-4351-b258-75697472a350/download](https://app.zenhub.com/files/152548651/eb612835-6935-4351-b258-75697472a350/download)

**Comment by aym19900825** [comment]
数据列新增两个字段
col{
	colType:   ''                          数据类型---折线或者柱状
	colAverage:  false                是否显示数据平均值
}

**Comment by aym19900825** [comment]
### 需确认添加参数：
视觉映射组件：
visualMap{
     max:    最大值
     min:     最小值
     outOfRangeColor: ''     超出范围颜色
     controllerColor: ''    控制条颜色
}

数据颜色渐变
col{
    colGradient: false   ，是否设置渐变
    colStartColor:  '',  渐变开始颜色 
    colEndColor:  '',  渐变结束颜色 
    colLabelRotate: ''   数据值旋转，  
}

y轴:
{
     ylineColor:            轴线颜色
     ynameColor:         y轴刻度颜色
     yaxisLabelPos:        刻度位置（inside或者正常）
}
y轴:
{
     xlineColor:            轴线颜色
     xnameColor:         y轴刻度颜色
     xaxisLabelPos:        刻度位置（inside或者正常）
}
subTit:  ''   echart的副标题

是否多y轴

是否提供主题模板颜色

**Comment by hklhai** [comment]
> subTit: '' echart的副标题
subTit: '' echart的副标题 什么意思？

**Comment by aym19900825** [comment]
折线图需添加特有参数：
数据列 （可能多个数据列轴）：
col{
   colAreaStyle: {}         面积图
    colSmooth:    'true'     曲线平滑
    colAreaColor: ''         面积颜色
    sampling: ''             降样策略
    colstep:'false'          阶梯图        
}

y轴（可能多个y轴）：
{
	ytype: 'value'  ----y轴显示方式
}

x轴(唯一一个)：
{
	xBoundaryGap: false,   是否留白
}

**Comment by aym19900825** [comment]
pie图需要添加参数
数据列
col{
	colRoseType: 'false'                                         '南丁格尔图'
	colLabelline: 'false',         				label线
	colLabelLineColor: '#c23531'   				label线颜色
	colRadius: 'pie'                            '环形图或饼状图'
}	

图例：
legendType: 'plain',
legendSelData:  []
