### ISSUE TITLE
列差集接口

### ISSUE THREAD

**Issue by hklhai** [hklhai/dashboard#33]
vid为传入的视图主键
GET http://127.0.0.1:8090/show/columnList?tablename=bar_source&dbid=1&vid=92

return：
[
    {
        "field": "showvalue2",
        "type": "double(10,2)"
    },
    {
        "field": "showvalue3",
        "type": "double(10,2)"
    },
    {
        "field": "showvalue4",
        "type": "double(10,2)"
    }
]

**Comment by aym19900825** [comment]
@hklhai 视图删除接口存在问题，删除数据前端给的正确，后端并未真正删除

**Comment by aym19900825** [comment]
@hklhai 新增存在问题，
![1](https://user-images.githubusercontent.com/19297811/49626743-2910ee00-fa16-11e8-84eb-b7823d0f6042.png)
![002](https://user-images.githubusercontent.com/19297811/49626752-30d09280-fa16-11e8-9bb0-b36fc4350008.png)
